wkt_user_link_add:
    path: profile/link/add/
    defaults:
        _controller: WKTUserBundle:Link:add
    requirements:
        id: \d+  

wk_user_link_get_ajax:
    path: /profile/link/getByAjax
    defaults:
        _controller: WKTUserBundle:Link:indexByUserWithAjax
    methods: [post]

wkt_user_link_index_by_user:
    path: /profile/link/index
    defaults:
        _controller: WKTUserBundle:Link:indexByUser


wkt_user_link_delete:
    path: /profile/link/delete/{id}
    methods: [post]
    defaults:
        _controller: WKTUserBundle:Link:delete
    requirements:
        id: \d+  

wkt_user_index:
    path: /admin/user/index
    defaults:
        _controller: WKTUserBundle:User:index

wkt_user_promote:
    path: /admin/user/promote/{id}
    defaults:
        _controller: WKTUserBundle:User:promoteUser
    requirements:
        id: \d+ 

wkt_user_demote:
    path: /admin/user/demote/{id}
    defaults:
        _controller: WKTUserBundle:User:demoteUser
    requirements:
        id: \d+

wkt_user_enabled:
    path: /admin/user/enabled/{id}/{activate}
    defaults:
        _controller: WKTUserBundle:User:enabledUser
    requirements:
        id: \d+
        activate : \d 

wkt_user_view_profile:
    path: /user/profile/{id}
    defaults:
        _controller: WKTUserBundle:User:viewProfile
    requirements:
        id: \d+

wkt_user_article_is_read:
    path: /user/articleIsRead/{id}
    defaults:
        _controller: WKTUserBundle:User:articleIsRead
    requirements:
        id: \d+ 

wkt_user_cancel_article_is_read:
    path: /user/cancel_articleIsRead/{id}
    defaults:
        _controller: WKTUserBundle:User:cancelIsRead
    requirements:
        id: \d+    

