# src/WKT/UserBundle/Resources/config/services.yml

services:
    wkt_user.confidence_score:
        class: WKT\UserBundle\ConfidenceScore\WKTConfidenceScore
        arguments: 
          - "@doctrine.orm.entity_manager"

    wkt_user.training_is_finished:
        class: WKT\UserBundle\TrainingIsFinished\WKTTrainingIsFinished
        arguments: 
          - "@doctrine.orm.entity_manager"
          - "@wkt_platform.summary"

    wkt_user.user_training_article_updated:
        class: WKT\UserBundle\UserTrainingAndArticleUpdated\WKTUserTrainingAndArticleUpdated
        arguments: 
          - "@doctrine.orm.entity_manager"

