imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    translator:      { fallbacks: ["%locale%"] }
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    port: 587
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: WKT\UserBundle\Entity\User
    from_email:
        # Adresse de l'expediteur
        address: no-reply@florian-garcia.com
        # Nom de l'expediteur
        sender_name: Admin WikiTech
    profile:
        form:
            type: WKT\UserBundle\Form\Type\ProfileFormType
    registration:
        confirmation:
            enabled: true
        form:
            type: WKT\UserBundle\Form\Type\RegistrationType

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
# app/config/config.yml

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

stfalcon_tinymce:
    tinymce_buttons:
        titre1: # Id of the first button
            title: "Titre 1"
            image: "asset[images/icones/a1.svg]"
        titre2: # Id of the first button
            title: "Titre 2"
            image: "asset[images/icones/a2.svg]"
        titreX: # Id of the first button
            title: "Paragraphe"
            image: "asset[images/icones/ax.svg]"
        accolade: # Id of the first button
            title: "Important"
            image: "asset[images/icones/{}.svg]"
        comment: # Id of the first button
            title: "Remarque"
            image: "asset[images/icones/|R.svg]"

    theme:
        # Simple theme: same as default theme
        simple:
            content_css: "asset[bundles/wktcore/tinymce-content.css]"
            height: 200
            relative_urls: false
            menubar: false
            forced_root_block: false
            force_p_newlines : true
            force_br_newlines : false
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor jbimages"
            toolbar1: "titre1 titre2 titreX accolade insertfile bullist numlist comment jbimages emoticons preview"

