wkt_user:
    resource: "@WKTUserBundle/Resources/config/routing.yml"
    prefix:   /

wkt_core:
    resource: "@WKTCoreBundle/Resources/config/routing.yml"
    prefix:   /

wkt_platform:
    resource: "@WKTPlatformBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /
