<?php

namespace WKT\UserBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLinksByUser($user)
	{
		$qb = $this->createQueryBuilder('l');
		return $qb->where('l.user = :user')
		        ->setParameter('user', $user)
		        ->innerJoin('l.social', 's')
		        ->addSelect('s.logo')
		        ->getQuery()
		        ->getArrayResult();
	}
}
