<?php

namespace WKT\UserBundle\Repository;

/**
 * UserArticleReadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserArticleReadRepository extends \Doctrine\ORM\EntityRepository
{
}
