<?php

namespace WKT\UserBundle\Repository;

use WKT\PlatformBundle\Entity\Training;
use WKT\UserBundle\Entity\User;

/**
 * UserTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTrainingRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserTrainingByUserAndTraining(User $user, Training $training)
	{
		return $this->createQueryBuilder('ut')
			->where('ut.user = :user')
			->setParameter('user', $user->getId())
			->andWhere('ut.training = :training')
			->setParameter('training', $training->getId())
			->getQuery()
			->getOneOrNullResult();
	}

}
