# src/WKT/PlatformBundle/Ressources/config/routing.yml

wkt_platform_index:
    path: /formation
    defaults:
        _controller: WKTPlatformBundle:Training:index

wkt_platform_view:
    path: /formation/{id}/{slugTraining}
    defaults:
        _controller: WKTPlatformBundle:Training:view
    requirements:
        id: \d+     

wkt_platform_add:
    path: /formation/add
    defaults:
        _controller: WKTPlatformBundle:Training:add

wkt_platform_article_view:
    path: /formation/{slugTraining}/article/{id}/{slugArticle}
    defaults:
        _controller: WKTPlatformBundle:Article:view
    requirements:
        id: \d+

wkt_platform_article_add:
    path: /article/add/{id}
    defaults:
        _controller: WKTPlatformBundle:Article:add
    requirements:
        id: \d+  

wkt_platform_part_add_ajax:
    path: /path/add/{id}
    defaults:
        _controller: WKTPlatformBundle:Part:addWithAjax
    requirements:
        id: \d+  

# Article Modified
wkt_platform_article_modified_add:
    path: /labo/add/{id}
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:add
    requirements:
        id: \d+  

wkt_platform_article_modified_index_by_article:
    path: /labo/index_by_article/{id}
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:indexByArticle
    requirements:
        id: \d+ 

wkt_platform_article_modified_index:
    path: /labo
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:index

wkt_platform_article_modified_view:
    path: /labo/article_modified/{id}
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:view
    requirements:
        id: \d+ 

wkt_platform_article_modified_edit:
    path: /labo/edit/{id}
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:edit
    requirements:
        id: \d+ 

wkt_platform_article_modified_delete:
    path: /labo/delete/{id}
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:delete
    requirements:
        id: \d+ 

wkt_platform_article_modified_add_new_article:
    path: /labo/add_article/{id}
    defaults:
        _controller: WKTPlatformBundle:ArticleModified:addNewArticle
    requirements:
        id: \d+ 















