# src/WKT/PlatformBundle/Resources/config/services.yml

services:
    wkt_platform.summary:
        class: WKT\PlatformBundle\Summary\WKTSummary
        arguments: 
          - "@doctrine.orm.entity_manager"
    wkt_platform.generate_form:
        class: WKT\PlatformBundle\GenerateForm\WKTGenerateForm
        arguments: 
          - "@doctrine.orm.entity_manager"
          - "@form.factory"
