<?php

namespace WKT\PlatformBundle\Repository;

/**
 * ArticleModifiedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleModifiedRepository extends \Doctrine\ORM\EntityRepository
{
}
