<?php

namespace WKT\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function summaryById($id)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->where('a.training = :id')
		     ->setParameter('id', $id)
		   ->orderBy('a.orderInTraining', 'ASC');


		return $qb
		  ->getQuery()
		  ->getResult();
	}
}
