<?php

namespace WKT\PlatformBundle\Repository;

use WKT\PlatformBundle\Entity\Article;

/**
 * ArticleModifiedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleModifiedRepository extends \Doctrine\ORM\EntityRepository
{
	public function getArticlesModifiedNotRejectedByArticle(Article $article)
	{
		return $this->createQueryBuilder('am')
			->where('am.article = :article')
				->setParameter('article', $article)
			->andWhere('am.isRejected IS NULL')
			->orderBy('am.id', 'DESC')
			->getQuery()
			->getResult();
	}
}
