<?php

namespace WKT\PlatformBundle\Repository;

use WKT\PlatformBundle\Entity\ArticleModified;
use WKT\PlatformBundle\Entity\Training;
use WKT\UserBundle\Entity\User;

/**
 * CommitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitRepository extends \Doctrine\ORM\EntityRepository
{
	public function countCommitsByArticleModified(ArticleModified $articleModified)
	{
		return $this->createQueryBuilder('c')
			->where('c.articleModified = :articleModified')
			->setParameter('articleModified', $articleModified->getId())
			->select('COUNT(c)')
			->getQuery()
			->getSingleScalarResult();
	}

	public function getCommitsValidateByUser(User $user)
	{
		return $this->createQueryBuilder('c')
			->where('c.user = :user')
				->setParameter('user', $user->getId())
			->andWhere('c.isValidate = :isValidate')
				->setParameter('isValidate', true)
			->getQuery()
			->getResult();
	}


}
