<?php

namespace WKT\PlatformBundle\Repository;

use WKT\PlatformBundle\Entity\ArticleModified;
use WKT\UserBundle\Entity\User;

/**
 * CommitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitRepository extends \Doctrine\ORM\EntityRepository
{
	public function countCommitsByArticleModified(ArticleModified $articleModified)
	{
		return $this->createQueryBuilder('c')
			->where('c.articleModified = :articleModified')
			->setParameter('articleModified', $articleModified->getId())
			->select('COUNT(c)')
			->getQuery()
			->getSingleScalarResult();
	}
}
