<?php

namespace WKT\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{
	public function queryBuilderTraining($id)
	{
	  return $this
	    ->createQueryBuilder('t')
	    ->where('t.id = :id')
	    ->setParameter('id', $id)
	  ;
	}
}
