<?php

namespace WKT\PlatformBundle\Repository;

/**
 * TypeOfModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfModificationRepository extends \Doctrine\ORM\EntityRepository
{
}
