<?php

namespace WKT\PlatformBundle\Repository;

/**
 * TypeOfModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfModificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function qbTypeOfModificationWithoutCreatePage()
	{
		return $this->createQueryBuilder('tom')
			->where('tom.type != :type')
			->setParameter('type', 'Création page')
			->orderBy('tom.id', 'ASC');
	}

}
