wkt_core_home:
    path:     /
    defaults: { _controller: WKTCoreBundle:Core:home }

wkt_core_contact_send_email:
    path:     /contact
    defaults: { _controller: WKTCoreBundle:Contact:sendEmail }

wkt_core_leaderboard:
    path:     /leaderboard
    defaults: { _controller: WKTCoreBundle:Core:leaderboard }
