services:
    kernel.listener.your_listener_name:
        class: WKT\CoreBundle\EventListener\CoreExceptionListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
